- name: Installation de WordPress
  hosts: wordpress
  become: true
  vars:
    # informations de la base de données
    db_name: wpdb
    db_user: wpuser
    db_password: wppassword
    # informations de WordPress
    wp_title: "My WordPress Site"
    wp_admin_user: admin
    wp_admin_password: admin123
    wp_admin_email: admin@example.com
  tasks:
    # Mise à jour des packages
    - name: Mise à jour des packages
      apt:
        update_cache: yes

    # Installation des packages nécessaires
    - name: Installation des packages nécessaires
      apt:
        name:
          - apache2
          - mariadb-server
          - php
          - libapache2-mod-php
          - php-mysql
          - python3-mysqldb
        state: latest

    # Configuration de la base de données
    - name: Configuration de la base de données
      mysql_db:
        name: "{{ db_name }}"
        state: present
      
    - name: Configuration de la base de données
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Création de l'utilisateur de la base de données
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        priv: "{{ db_name }}.*:ALL"
        state: present

    # Téléchargement et installation de WordPress
    - name: Téléchargement et installation de WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    - name: Extraction de WordPress
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/html/"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Configuration de WordPress
      template:
        src: ./wp-config.php.j2
        dest: "/var/www/html/wp-config.php"
        mode: "0640"

    # Configuration d'Apache
    - name: Activation du module Apache
      apache2_module:
        name: rewrite
        state: present

    - name: Configuration d'Apache pour WordPress
      template:
        src: ./wordpress.conf.j2
        dest: "/etc/apache2/sites-available/wordpress.conf"
        mode: "0640"

    - name: Modification du propriétaire de /var/www/html
      become: true
      file:
        path: "/var/www/html"
        owner: www-data
        group: www-data
        recurse: yes


    # Redémarrage d'Apache
    - name: Redémarrage d'Apache
      service:
        name: apache2
        state: restarted

    - name: Renommage de index.html en index.html.old
      become: true
      command: mv /var/www/html/index.html /var/www/html/index.html.old